# Generated by Django 4.1.6 on 2023-02-27 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hodnoceni',
            fields=[
                ('idhodnoceni', models.AutoField(db_column='idHodnoceni', primary_key=True, serialize=False)),
                ('nazev', models.CharField(blank=True, db_column='Nazev', max_length=100, null=True)),
                ('doporuceni', models.IntegerField(blank=True, db_column='Doporuceni', null=True)),
                ('text_recenze', models.TextField(blank=True, db_column='Text_recenze', null=True)),
            ],
            options={
                'db_table': 'hodnoceni',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hry',
            fields=[
                ('idhry', models.AutoField(db_column='idHry', primary_key=True, serialize=False)),
                ('nazev', models.CharField(blank=True, db_column='Nazev', max_length=45, null=True)),
                ('cena_v_eur', models.FloatField(blank=True, db_column='Cena_v_eur', null=True)),
                ('trzby_v_eur', models.FloatField(blank=True, db_column='Trzby_v_eur', null=True)),
                ('prodanych_kusu', models.IntegerField(blank=True, db_column='Prodanych_kusu', null=True)),
            ],
            options={
                'db_table': 'hry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('idpublisher', models.AutoField(db_column='idPublisher', primary_key=True, serialize=False)),
                ('nazev', models.CharField(blank=True, db_column='Nazev', max_length=128, null=True)),
                ('popis', models.TextField(blank=True, db_column='Popis', null=True)),
            ],
            options={
                'db_table': 'publisher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uzivatele',
            fields=[
                ('iduzivatele', models.AutoField(db_column='idUzivatele', primary_key=True, serialize=False)),
                ('nick', models.CharField(blank=True, db_column='Nick', max_length=45, null=True)),
                ('heslo', models.CharField(blank=True, db_column='Heslo', max_length=45, null=True)),
                ('vlastneno_her', models.IntegerField(blank=True, db_column='Vlastneno_her', null=True)),
                ('uzivatelske_jmeno', models.CharField(blank=True, db_column='Uzivatelske_jmeno', max_length=64, null=True)),
                ('level', models.SmallIntegerField(blank=True, db_column='Level', null=True)),
            ],
            options={
                'db_table': 'uzivatele',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vyvojar',
            fields=[
                ('idvyvojar', models.AutoField(db_column='idVyvojar', primary_key=True, serialize=False)),
                ('nazev', models.CharField(blank=True, db_column='Nazev', max_length=45, null=True)),
                ('popis', models.TextField(blank=True, db_column='Popis', null=True)),
            ],
            options={
                'db_table': 'vyvojar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zanr',
            fields=[
                ('idzanr', models.AutoField(db_column='idZanr', primary_key=True, serialize=False)),
                ('nazev', models.CharField(blank=True, db_column='Nazev', max_length=64, null=True)),
            ],
            options={
                'db_table': 'zanr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HryHasUzivatele',
            fields=[
                ('hry_idhry', models.OneToOneField(db_column='Hry_idHry', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.hry')),
            ],
            options={
                'db_table': 'hry_has_uzivatele',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HryHasZanr',
            fields=[
                ('hry_idhry', models.OneToOneField(db_column='Hry_idHry', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.hry')),
            ],
            options={
                'db_table': 'hry_has_zanr',
                'managed': False,
            },
        ),
    ]
